["!! INITIAL SETTINGS -- DO NOT CHANGE !!"]
checkhash = "#- V_p_4YV3IJV6ye4eIXKX -#"
level = 15
mem = 32
threads = 2
[sites."vitiral@reddit.com"]
"!! fmt !!" = "{p:.20}"
"!! pin !!" = false
"!! salt !!" = "vitiral@reddit.com0vitiral@reddit.com0vitiral@reddit.com0vitiral@reddit.com0"
notes = ""
